/* Auto generated by: sym_extract.py /home/sobomax/projects/freebsd13/sys/sys syms_sys.econf */
/* From Git revision: 74b6c983723cf3d3e277f10780ad081e32c80e80 branch: releng/14.1 */

/* Defines: */
#undef EJUSTRETURN /* found in: sys/errno.h */
#define	EJUSTRETURN	(-2)		/* don't modify regs, just return */
#undef O_ACCMODE /* found in: sys/fcntl.h */
#define	O_ACCMODE	0x0003		/* mask for above modes */
#undef O_WRONLY /* found in: sys/fcntl.h */
#define	O_WRONLY	0x0001		/* open for writing only */
#undef O_RDWR /* found in: sys/fcntl.h */
#define	O_RDWR		0x0002		/* open for reading and writing */
#undef O_CREAT /* found in: sys/fcntl.h */
#define	O_CREAT		0x0200		/* create if nonexistent */
#undef O_EXCL /* found in: sys/fcntl.h */
#define	O_EXCL		0x0800		/* error if already exists */
#undef O_NOCTTY /* found in: sys/fcntl.h */
#define	O_NOCTTY	0x8000		/* don't assign controlling terminal */
#undef O_TRUNC /* found in: sys/fcntl.h */
#define	O_TRUNC		0x0400		/* truncate to zero length */
#undef O_APPEND /* found in: sys/fcntl.h */
#define	O_APPEND	0x0008		/* set append mode */
#undef O_NONBLOCK /* found in: sys/fcntl.h */
#define	O_NONBLOCK	0x0004		/* no delay */
#undef O_SYNC /* found in: sys/fcntl.h */
#define	O_SYNC		0x0080		/* POSIX synonym for O_FSYNC */
#undef O_DIRECTORY /* found in: sys/fcntl.h */
#define	O_DIRECTORY	0x00020000	/* Fail if not directory */
#undef O_NOFOLLOW /* found in: sys/fcntl.h */
#define	O_NOFOLLOW	0x0100		/* don't follow symlinks */
#undef O_DIRECT /* found in: sys/fcntl.h */
#define	O_DIRECT	0x00010000
#undef O_CLOEXEC /* found in: sys/fcntl.h */
#define	O_CLOEXEC	0x00100000
#undef O_PATH /* found in: sys/fcntl.h */
#define O_PATH		0x00400000	/* fd is only a path */
#undef O_DSYNC /* found in: sys/fcntl.h */
#define	O_DSYNC		0x01000000	/* POSIX data sync */
#undef KENV_GET /* found in: sys/kenv.h */
#define KENV_GET		0
#undef MAP_GUARD /* found in: sys/mman.h */
#define	MAP_GUARD	 0x00002000 /* reserve but don't map address range */
#undef MAP_FIXED /* found in: sys/mman.h */
#define	MAP_FIXED	 0x0010	/* map addr must be exactly as requested */
#undef MAP_ANON /* found in: sys/mman.h */
#define	MAP_ANON	 0x1000	/* allocated from memory, swap space */
#undef MAP_EXCL /* found in: sys/mman.h */
#define	MAP_EXCL	 0x00004000 /* for MAP_FIXED, fail if address is used */
#undef MAP_PRIVATE /* found in: sys/mman.h */
#define	MAP_PRIVATE	0x0002		/* changes are private */
#undef MAP_SHARED /* found in: sys/mman.h */
#define	MAP_SHARED	0x0001		/* share changes */
#undef MAP_NOCORE /* found in: sys/mman.h */
#define	MAP_NOCORE	 0x00020000 /* dont include these pages in a coredump */
#undef MAP_STACK /* found in: sys/mman.h */
#define	MAP_STACK	 0x0400	/* region grows down, like a stack */
#undef MAP_PREFAULT_READ /* found in: sys/mman.h */
#define	MAP_PREFAULT_READ 0x00040000 /* prefault mapping for reading */
#undef MAP_ALIGNMENT_SHIFT /* found in: sys/mman.h */
#define	MAP_ALIGNMENT_SHIFT	24
#undef MAP_ALIGNED /* found in: sys/mman.h */
#define	MAP_ALIGNED(n)	 ((n) << MAP_ALIGNMENT_SHIFT)
#undef MAP_ALIGNMENT_MASK /* found in: sys/mman.h */
#define	MAP_ALIGNMENT_MASK	MAP_ALIGNED(0xff)
#undef SHM_ANON /* found in: sys/mman.h */
#define	SHM_ANON		((char *)1)
#undef __FreeBSD_version /* found in: sys/param.h */
#define __FreeBSD_version 1401000
#undef INFTIM /* found in: sys/poll.h */
#define	INFTIM		(-1)
#undef NET_RT_IFLISTL /* found in: sys/socket.h */
#define	NET_RT_IFLISTL	5		/* Survey interface list, using 'l'en */
#undef SO_NOSIGPIPE /* found in: sys/socket.h */
#define	SO_NOSIGPIPE	0x00000800	/* no SIGPIPE from EPIPE */
#undef SO_BINTIME /* found in: sys/socket.h */
#define	SO_BINTIME	0x00002000	/* timestamp received dgram traffic */
#undef SO_LISTENINCQLEN /* found in: sys/socket.h */
#define	SO_LISTENINCQLEN	0x1013	/* socket's incomplete queue length */
#undef SYS_exit /* found in: sys/syscall.h */
#define	SYS_exit	1
#undef SYS_fork /* found in: sys/syscall.h */
#define	SYS_fork	2
#undef SYS_read /* found in: sys/syscall.h */
#define	SYS_read	3
#undef SYS_write /* found in: sys/syscall.h */
#define	SYS_write	4
#undef SYS_open /* found in: sys/syscall.h */
#define	SYS_open	5
#undef SYS_close /* found in: sys/syscall.h */
#define	SYS_close	6
#undef SYS_wait4 /* found in: sys/syscall.h */
#define	SYS_wait4	7
#undef SYS_link /* found in: sys/syscall.h */
#define	SYS_link	9
#undef SYS_unlink /* found in: sys/syscall.h */
#define	SYS_unlink	10
#undef SYS_chdir /* found in: sys/syscall.h */
#define	SYS_chdir	12
#undef SYS_fchdir /* found in: sys/syscall.h */
#define	SYS_fchdir	13
#undef SYS_freebsd11_mknod /* found in: sys/syscall.h */
#define	SYS_freebsd11_mknod	14
#undef SYS_chmod /* found in: sys/syscall.h */
#define	SYS_chmod	15
#undef SYS_chown /* found in: sys/syscall.h */
#define	SYS_chown	16
#undef SYS_break /* found in: sys/syscall.h */
#define	SYS_break	17
#undef SYS_getpid /* found in: sys/syscall.h */
#define	SYS_getpid	20
#undef SYS_mount /* found in: sys/syscall.h */
#define	SYS_mount	21
#undef SYS_unmount /* found in: sys/syscall.h */
#define	SYS_unmount	22
#undef SYS_setuid /* found in: sys/syscall.h */
#define	SYS_setuid	23
#undef SYS_getuid /* found in: sys/syscall.h */
#define	SYS_getuid	24
#undef SYS_geteuid /* found in: sys/syscall.h */
#define	SYS_geteuid	25
#undef SYS_ptrace /* found in: sys/syscall.h */
#define	SYS_ptrace	26
#undef SYS_recvmsg /* found in: sys/syscall.h */
#define	SYS_recvmsg	27
#undef SYS_sendmsg /* found in: sys/syscall.h */
#define	SYS_sendmsg	28
#undef SYS_recvfrom /* found in: sys/syscall.h */
#define	SYS_recvfrom	29
#undef SYS_accept /* found in: sys/syscall.h */
#define	SYS_accept	30
#undef SYS_getpeername /* found in: sys/syscall.h */
#define	SYS_getpeername	31
#undef SYS_getsockname /* found in: sys/syscall.h */
#define	SYS_getsockname	32
#undef SYS_access /* found in: sys/syscall.h */
#define	SYS_access	33
#undef SYS_chflags /* found in: sys/syscall.h */
#define	SYS_chflags	34
#undef SYS_fchflags /* found in: sys/syscall.h */
#define	SYS_fchflags	35
#undef SYS_sync /* found in: sys/syscall.h */
#define	SYS_sync	36
#undef SYS_kill /* found in: sys/syscall.h */
#define	SYS_kill	37
#undef SYS_getppid /* found in: sys/syscall.h */
#define	SYS_getppid	39
#undef SYS_dup /* found in: sys/syscall.h */
#define	SYS_dup	41
#undef SYS_freebsd10_pipe /* found in: sys/syscall.h */
#define	SYS_freebsd10_pipe	42
#undef SYS_getegid /* found in: sys/syscall.h */
#define	SYS_getegid	43
#undef SYS_profil /* found in: sys/syscall.h */
#define	SYS_profil	44
#undef SYS_ktrace /* found in: sys/syscall.h */
#define	SYS_ktrace	45
#undef SYS_getgid /* found in: sys/syscall.h */
#define	SYS_getgid	47
#undef SYS_getlogin /* found in: sys/syscall.h */
#define	SYS_getlogin	49
#undef SYS_setlogin /* found in: sys/syscall.h */
#define	SYS_setlogin	50
#undef SYS_acct /* found in: sys/syscall.h */
#define	SYS_acct	51
#undef SYS_sigaltstack /* found in: sys/syscall.h */
#define	SYS_sigaltstack	53
#undef SYS_ioctl /* found in: sys/syscall.h */
#define	SYS_ioctl	54
#undef SYS_reboot /* found in: sys/syscall.h */
#define	SYS_reboot	55
#undef SYS_revoke /* found in: sys/syscall.h */
#define	SYS_revoke	56
#undef SYS_symlink /* found in: sys/syscall.h */
#define	SYS_symlink	57
#undef SYS_readlink /* found in: sys/syscall.h */
#define	SYS_readlink	58
#undef SYS_execve /* found in: sys/syscall.h */
#define	SYS_execve	59
#undef SYS_umask /* found in: sys/syscall.h */
#define	SYS_umask	60
#undef SYS_chroot /* found in: sys/syscall.h */
#define	SYS_chroot	61
#undef SYS_msync /* found in: sys/syscall.h */
#define	SYS_msync	65
#undef SYS_vfork /* found in: sys/syscall.h */
#define	SYS_vfork	66
#undef SYS_sbrk /* found in: sys/syscall.h */
#define	SYS_sbrk	69
#undef SYS_sstk /* found in: sys/syscall.h */
#define	SYS_sstk	70
#undef SYS_freebsd11_vadvise /* found in: sys/syscall.h */
#define	SYS_freebsd11_vadvise	72
#undef SYS_munmap /* found in: sys/syscall.h */
#define	SYS_munmap	73
#undef SYS_mprotect /* found in: sys/syscall.h */
#define	SYS_mprotect	74
#undef SYS_madvise /* found in: sys/syscall.h */
#define	SYS_madvise	75
#undef SYS_mincore /* found in: sys/syscall.h */
#define	SYS_mincore	78
#undef SYS_getgroups /* found in: sys/syscall.h */
#define	SYS_getgroups	79
#undef SYS_setgroups /* found in: sys/syscall.h */
#define	SYS_setgroups	80
#undef SYS_getpgrp /* found in: sys/syscall.h */
#define	SYS_getpgrp	81
#undef SYS_setpgid /* found in: sys/syscall.h */
#define	SYS_setpgid	82
#undef SYS_setitimer /* found in: sys/syscall.h */
#define	SYS_setitimer	83
#undef SYS_swapon /* found in: sys/syscall.h */
#define	SYS_swapon	85
#undef SYS_getitimer /* found in: sys/syscall.h */
#define	SYS_getitimer	86
#undef SYS_getdtablesize /* found in: sys/syscall.h */
#define	SYS_getdtablesize	89
#undef SYS_dup2 /* found in: sys/syscall.h */
#define	SYS_dup2	90
#undef SYS_fcntl /* found in: sys/syscall.h */
#define	SYS_fcntl	92
#undef SYS_select /* found in: sys/syscall.h */
#define	SYS_select	93
#undef SYS_fsync /* found in: sys/syscall.h */
#define	SYS_fsync	95
#undef SYS_setpriority /* found in: sys/syscall.h */
#define	SYS_setpriority	96
#undef SYS_socket /* found in: sys/syscall.h */
#define	SYS_socket	97
#undef SYS_connect /* found in: sys/syscall.h */
#define	SYS_connect	98
#undef SYS_getpriority /* found in: sys/syscall.h */
#define	SYS_getpriority	100
#undef SYS_bind /* found in: sys/syscall.h */
#define	SYS_bind	104
#undef SYS_setsockopt /* found in: sys/syscall.h */
#define	SYS_setsockopt	105
#undef SYS_listen /* found in: sys/syscall.h */
#define	SYS_listen	106
#undef SYS_gettimeofday /* found in: sys/syscall.h */
#define	SYS_gettimeofday	116
#undef SYS_getrusage /* found in: sys/syscall.h */
#define	SYS_getrusage	117
#undef SYS_getsockopt /* found in: sys/syscall.h */
#define	SYS_getsockopt	118
#undef SYS_readv /* found in: sys/syscall.h */
#define	SYS_readv	120
#undef SYS_writev /* found in: sys/syscall.h */
#define	SYS_writev	121
#undef SYS_settimeofday /* found in: sys/syscall.h */
#define	SYS_settimeofday	122
#undef SYS_fchown /* found in: sys/syscall.h */
#define	SYS_fchown	123
#undef SYS_fchmod /* found in: sys/syscall.h */
#define	SYS_fchmod	124
#undef SYS_setreuid /* found in: sys/syscall.h */
#define	SYS_setreuid	126
#undef SYS_setregid /* found in: sys/syscall.h */
#define	SYS_setregid	127
#undef SYS_rename /* found in: sys/syscall.h */
#define	SYS_rename	128
#undef SYS_flock /* found in: sys/syscall.h */
#define	SYS_flock	131
#undef SYS_mkfifo /* found in: sys/syscall.h */
#define	SYS_mkfifo	132
#undef SYS_sendto /* found in: sys/syscall.h */
#define	SYS_sendto	133
#undef SYS_shutdown /* found in: sys/syscall.h */
#define	SYS_shutdown	134
#undef SYS_socketpair /* found in: sys/syscall.h */
#define	SYS_socketpair	135
#undef SYS_mkdir /* found in: sys/syscall.h */
#define	SYS_mkdir	136
#undef SYS_rmdir /* found in: sys/syscall.h */
#define	SYS_rmdir	137
#undef SYS_utimes /* found in: sys/syscall.h */
#define	SYS_utimes	138
#undef SYS_adjtime /* found in: sys/syscall.h */
#define	SYS_adjtime	140
#undef SYS_setsid /* found in: sys/syscall.h */
#define	SYS_setsid	147
#undef SYS_quotactl /* found in: sys/syscall.h */
#define	SYS_quotactl	148
#undef SYS_nlm_syscall /* found in: sys/syscall.h */
#define	SYS_nlm_syscall	154
#undef SYS_nfssvc /* found in: sys/syscall.h */
#define	SYS_nfssvc	155
#undef SYS_lgetfh /* found in: sys/syscall.h */
#define	SYS_lgetfh	160
#undef SYS_getfh /* found in: sys/syscall.h */
#define	SYS_getfh	161
#undef SYS_sysarch /* found in: sys/syscall.h */
#define	SYS_sysarch	165
#undef SYS_rtprio /* found in: sys/syscall.h */
#define	SYS_rtprio	166
#undef SYS_semsys /* found in: sys/syscall.h */
#define	SYS_semsys	169
#undef SYS_msgsys /* found in: sys/syscall.h */
#define	SYS_msgsys	170
#undef SYS_shmsys /* found in: sys/syscall.h */
#define	SYS_shmsys	171
#undef SYS_setfib /* found in: sys/syscall.h */
#define	SYS_setfib	175
#undef SYS_ntp_adjtime /* found in: sys/syscall.h */
#define	SYS_ntp_adjtime	176
#undef SYS_setgid /* found in: sys/syscall.h */
#define	SYS_setgid	181
#undef SYS_setegid /* found in: sys/syscall.h */
#define	SYS_setegid	182
#undef SYS_seteuid /* found in: sys/syscall.h */
#define	SYS_seteuid	183
#undef SYS_freebsd11_stat /* found in: sys/syscall.h */
#define	SYS_freebsd11_stat	188
#undef SYS_freebsd11_fstat /* found in: sys/syscall.h */
#define	SYS_freebsd11_fstat	189
#undef SYS_freebsd11_lstat /* found in: sys/syscall.h */
#define	SYS_freebsd11_lstat	190
#undef SYS_pathconf /* found in: sys/syscall.h */
#define	SYS_pathconf	191
#undef SYS_fpathconf /* found in: sys/syscall.h */
#define	SYS_fpathconf	192
#undef SYS_getrlimit /* found in: sys/syscall.h */
#define	SYS_getrlimit	194
#undef SYS_setrlimit /* found in: sys/syscall.h */
#define	SYS_setrlimit	195
#undef SYS_freebsd11_getdirentries /* found in: sys/syscall.h */
#define	SYS_freebsd11_getdirentries	196
#undef SYS___sysctl /* found in: sys/syscall.h */
#define	SYS___sysctl	202
#undef SYS_mlock /* found in: sys/syscall.h */
#define	SYS_mlock	203
#undef SYS_munlock /* found in: sys/syscall.h */
#define	SYS_munlock	204
#undef SYS_undelete /* found in: sys/syscall.h */
#define	SYS_undelete	205
#undef SYS_futimes /* found in: sys/syscall.h */
#define	SYS_futimes	206
#undef SYS_getpgid /* found in: sys/syscall.h */
#define	SYS_getpgid	207
#undef SYS_poll /* found in: sys/syscall.h */
#define	SYS_poll	209
#undef SYS_freebsd7___semctl /* found in: sys/syscall.h */
#define	SYS_freebsd7___semctl	220
#undef SYS_semget /* found in: sys/syscall.h */
#define	SYS_semget	221
#undef SYS_semop /* found in: sys/syscall.h */
#define	SYS_semop	222
#undef SYS_freebsd7_msgctl /* found in: sys/syscall.h */
#define	SYS_freebsd7_msgctl	224
#undef SYS_msgget /* found in: sys/syscall.h */
#define	SYS_msgget	225
#undef SYS_msgsnd /* found in: sys/syscall.h */
#define	SYS_msgsnd	226
#undef SYS_msgrcv /* found in: sys/syscall.h */
#define	SYS_msgrcv	227
#undef SYS_shmat /* found in: sys/syscall.h */
#define	SYS_shmat	228
#undef SYS_freebsd7_shmctl /* found in: sys/syscall.h */
#define	SYS_freebsd7_shmctl	229
#undef SYS_shmdt /* found in: sys/syscall.h */
#define	SYS_shmdt	230
#undef SYS_shmget /* found in: sys/syscall.h */
#define	SYS_shmget	231
#undef SYS_clock_gettime /* found in: sys/syscall.h */
#define	SYS_clock_gettime	232
#undef SYS_clock_settime /* found in: sys/syscall.h */
#define	SYS_clock_settime	233
#undef SYS_clock_getres /* found in: sys/syscall.h */
#define	SYS_clock_getres	234
#undef SYS_ktimer_create /* found in: sys/syscall.h */
#define	SYS_ktimer_create	235
#undef SYS_ktimer_delete /* found in: sys/syscall.h */
#define	SYS_ktimer_delete	236
#undef SYS_ktimer_settime /* found in: sys/syscall.h */
#define	SYS_ktimer_settime	237
#undef SYS_ktimer_gettime /* found in: sys/syscall.h */
#define	SYS_ktimer_gettime	238
#undef SYS_ktimer_getoverrun /* found in: sys/syscall.h */
#define	SYS_ktimer_getoverrun	239
#undef SYS_nanosleep /* found in: sys/syscall.h */
#define	SYS_nanosleep	240
#undef SYS_ffclock_getcounter /* found in: sys/syscall.h */
#define	SYS_ffclock_getcounter	241
#undef SYS_ffclock_setestimate /* found in: sys/syscall.h */
#define	SYS_ffclock_setestimate	242
#undef SYS_ffclock_getestimate /* found in: sys/syscall.h */
#define	SYS_ffclock_getestimate	243
#undef SYS_clock_nanosleep /* found in: sys/syscall.h */
#define	SYS_clock_nanosleep	244
#undef SYS_clock_getcpuclockid2 /* found in: sys/syscall.h */
#define	SYS_clock_getcpuclockid2	247
#undef SYS_ntp_gettime /* found in: sys/syscall.h */
#define	SYS_ntp_gettime	248
#undef SYS_minherit /* found in: sys/syscall.h */
#define	SYS_minherit	250
#undef SYS_rfork /* found in: sys/syscall.h */
#define	SYS_rfork	251
#undef SYS_issetugid /* found in: sys/syscall.h */
#define	SYS_issetugid	253
#undef SYS_lchown /* found in: sys/syscall.h */
#define	SYS_lchown	254
#undef SYS_aio_read /* found in: sys/syscall.h */
#define	SYS_aio_read	255
#undef SYS_aio_write /* found in: sys/syscall.h */
#define	SYS_aio_write	256
#undef SYS_lio_listio /* found in: sys/syscall.h */
#define	SYS_lio_listio	257
#undef SYS_freebsd11_getdents /* found in: sys/syscall.h */
#define	SYS_freebsd11_getdents	272
#undef SYS_lchmod /* found in: sys/syscall.h */
#define	SYS_lchmod	274
#undef SYS_lutimes /* found in: sys/syscall.h */
#define	SYS_lutimes	276
#undef SYS_freebsd11_nstat /* found in: sys/syscall.h */
#define	SYS_freebsd11_nstat	278
#undef SYS_freebsd11_nfstat /* found in: sys/syscall.h */
#define	SYS_freebsd11_nfstat	279
#undef SYS_freebsd11_nlstat /* found in: sys/syscall.h */
#define	SYS_freebsd11_nlstat	280
#undef SYS_preadv /* found in: sys/syscall.h */
#define	SYS_preadv	289
#undef SYS_pwritev /* found in: sys/syscall.h */
#define	SYS_pwritev	290
#undef SYS_fhopen /* found in: sys/syscall.h */
#define	SYS_fhopen	298
#undef SYS_freebsd11_fhstat /* found in: sys/syscall.h */
#define	SYS_freebsd11_fhstat	299
#undef SYS_modnext /* found in: sys/syscall.h */
#define	SYS_modnext	300
#undef SYS_modstat /* found in: sys/syscall.h */
#define	SYS_modstat	301
#undef SYS_modfnext /* found in: sys/syscall.h */
#define	SYS_modfnext	302
#undef SYS_modfind /* found in: sys/syscall.h */
#define	SYS_modfind	303
#undef SYS_kldload /* found in: sys/syscall.h */
#define	SYS_kldload	304
#undef SYS_kldunload /* found in: sys/syscall.h */
#define	SYS_kldunload	305
#undef SYS_kldfind /* found in: sys/syscall.h */
#define	SYS_kldfind	306
#undef SYS_kldnext /* found in: sys/syscall.h */
#define	SYS_kldnext	307
#undef SYS_kldstat /* found in: sys/syscall.h */
#define	SYS_kldstat	308
#undef SYS_kldfirstmod /* found in: sys/syscall.h */
#define	SYS_kldfirstmod	309
#undef SYS_getsid /* found in: sys/syscall.h */
#define	SYS_getsid	310
#undef SYS_setresuid /* found in: sys/syscall.h */
#define	SYS_setresuid	311
#undef SYS_setresgid /* found in: sys/syscall.h */
#define	SYS_setresgid	312
#undef SYS_aio_return /* found in: sys/syscall.h */
#define	SYS_aio_return	314
#undef SYS_aio_suspend /* found in: sys/syscall.h */
#define	SYS_aio_suspend	315
#undef SYS_aio_cancel /* found in: sys/syscall.h */
#define	SYS_aio_cancel	316
#undef SYS_aio_error /* found in: sys/syscall.h */
#define	SYS_aio_error	317
#undef SYS_yield /* found in: sys/syscall.h */
#define	SYS_yield	321
#undef SYS_mlockall /* found in: sys/syscall.h */
#define	SYS_mlockall	324
#undef SYS_munlockall /* found in: sys/syscall.h */
#define	SYS_munlockall	325
#undef SYS___getcwd /* found in: sys/syscall.h */
#define	SYS___getcwd	326
#undef SYS_sched_setparam /* found in: sys/syscall.h */
#define	SYS_sched_setparam	327
#undef SYS_sched_getparam /* found in: sys/syscall.h */
#define	SYS_sched_getparam	328
#undef SYS_sched_setscheduler /* found in: sys/syscall.h */
#define	SYS_sched_setscheduler	329
#undef SYS_sched_getscheduler /* found in: sys/syscall.h */
#define	SYS_sched_getscheduler	330
#undef SYS_sched_yield /* found in: sys/syscall.h */
#define	SYS_sched_yield	331
#undef SYS_sched_get_priority_max /* found in: sys/syscall.h */
#define	SYS_sched_get_priority_max	332
#undef SYS_sched_get_priority_min /* found in: sys/syscall.h */
#define	SYS_sched_get_priority_min	333
#undef SYS_sched_rr_get_interval /* found in: sys/syscall.h */
#define	SYS_sched_rr_get_interval	334
#undef SYS_utrace /* found in: sys/syscall.h */
#define	SYS_utrace	335
#undef SYS_kldsym /* found in: sys/syscall.h */
#define	SYS_kldsym	337
#undef SYS_jail /* found in: sys/syscall.h */
#define	SYS_jail	338
#undef SYS_nnpfs_syscall /* found in: sys/syscall.h */
#define	SYS_nnpfs_syscall	339
#undef SYS_sigprocmask /* found in: sys/syscall.h */
#define	SYS_sigprocmask	340
#undef SYS_sigsuspend /* found in: sys/syscall.h */
#define	SYS_sigsuspend	341
#undef SYS_sigpending /* found in: sys/syscall.h */
#define	SYS_sigpending	343
#undef SYS_sigtimedwait /* found in: sys/syscall.h */
#define	SYS_sigtimedwait	345
#undef SYS_sigwaitinfo /* found in: sys/syscall.h */
#define	SYS_sigwaitinfo	346
#undef SYS___acl_get_file /* found in: sys/syscall.h */
#define	SYS___acl_get_file	347
#undef SYS___acl_set_file /* found in: sys/syscall.h */
#define	SYS___acl_set_file	348
#undef SYS___acl_get_fd /* found in: sys/syscall.h */
#define	SYS___acl_get_fd	349
#undef SYS___acl_set_fd /* found in: sys/syscall.h */
#define	SYS___acl_set_fd	350
#undef SYS___acl_delete_file /* found in: sys/syscall.h */
#define	SYS___acl_delete_file	351
#undef SYS___acl_delete_fd /* found in: sys/syscall.h */
#define	SYS___acl_delete_fd	352
#undef SYS___acl_aclcheck_file /* found in: sys/syscall.h */
#define	SYS___acl_aclcheck_file	353
#undef SYS___acl_aclcheck_fd /* found in: sys/syscall.h */
#define	SYS___acl_aclcheck_fd	354
#undef SYS_extattrctl /* found in: sys/syscall.h */
#define	SYS_extattrctl	355
#undef SYS_extattr_set_file /* found in: sys/syscall.h */
#define	SYS_extattr_set_file	356
#undef SYS_extattr_get_file /* found in: sys/syscall.h */
#define	SYS_extattr_get_file	357
#undef SYS_extattr_delete_file /* found in: sys/syscall.h */
#define	SYS_extattr_delete_file	358
#undef SYS_aio_waitcomplete /* found in: sys/syscall.h */
#define	SYS_aio_waitcomplete	359
#undef SYS_getresuid /* found in: sys/syscall.h */
#define	SYS_getresuid	360
#undef SYS_getresgid /* found in: sys/syscall.h */
#define	SYS_getresgid	361
#undef SYS_kqueue /* found in: sys/syscall.h */
#define	SYS_kqueue	362
#undef SYS_freebsd11_kevent /* found in: sys/syscall.h */
#define	SYS_freebsd11_kevent	363
#undef SYS_extattr_set_fd /* found in: sys/syscall.h */
#define	SYS_extattr_set_fd	371
#undef SYS_extattr_get_fd /* found in: sys/syscall.h */
#define	SYS_extattr_get_fd	372
#undef SYS_extattr_delete_fd /* found in: sys/syscall.h */
#define	SYS_extattr_delete_fd	373
#undef SYS___setugid /* found in: sys/syscall.h */
#define	SYS___setugid	374
#undef SYS_eaccess /* found in: sys/syscall.h */
#define	SYS_eaccess	376
#undef SYS_afs3_syscall /* found in: sys/syscall.h */
#define	SYS_afs3_syscall	377
#undef SYS_nmount /* found in: sys/syscall.h */
#define	SYS_nmount	378
#undef SYS___mac_get_proc /* found in: sys/syscall.h */
#define	SYS___mac_get_proc	384
#undef SYS___mac_set_proc /* found in: sys/syscall.h */
#define	SYS___mac_set_proc	385
#undef SYS___mac_get_fd /* found in: sys/syscall.h */
#define	SYS___mac_get_fd	386
#undef SYS___mac_get_file /* found in: sys/syscall.h */
#define	SYS___mac_get_file	387
#undef SYS___mac_set_fd /* found in: sys/syscall.h */
#define	SYS___mac_set_fd	388
#undef SYS___mac_set_file /* found in: sys/syscall.h */
#define	SYS___mac_set_file	389
#undef SYS_kenv /* found in: sys/syscall.h */
#define	SYS_kenv	390
#undef SYS_lchflags /* found in: sys/syscall.h */
#define	SYS_lchflags	391
#undef SYS_uuidgen /* found in: sys/syscall.h */
#define	SYS_uuidgen	392
#undef SYS_sendfile /* found in: sys/syscall.h */
#define	SYS_sendfile	393
#undef SYS_mac_syscall /* found in: sys/syscall.h */
#define	SYS_mac_syscall	394
#undef SYS_freebsd11_getfsstat /* found in: sys/syscall.h */
#define	SYS_freebsd11_getfsstat	395
#undef SYS_freebsd11_statfs /* found in: sys/syscall.h */
#define	SYS_freebsd11_statfs	396
#undef SYS_freebsd11_fstatfs /* found in: sys/syscall.h */
#define	SYS_freebsd11_fstatfs	397
#undef SYS_freebsd11_fhstatfs /* found in: sys/syscall.h */
#define	SYS_freebsd11_fhstatfs	398
#undef SYS_ksem_close /* found in: sys/syscall.h */
#define	SYS_ksem_close	400
#undef SYS_ksem_post /* found in: sys/syscall.h */
#define	SYS_ksem_post	401
#undef SYS_ksem_wait /* found in: sys/syscall.h */
#define	SYS_ksem_wait	402
#undef SYS_ksem_trywait /* found in: sys/syscall.h */
#define	SYS_ksem_trywait	403
#undef SYS_ksem_init /* found in: sys/syscall.h */
#define	SYS_ksem_init	404
#undef SYS_ksem_open /* found in: sys/syscall.h */
#define	SYS_ksem_open	405
#undef SYS_ksem_unlink /* found in: sys/syscall.h */
#define	SYS_ksem_unlink	406
#undef SYS_ksem_getvalue /* found in: sys/syscall.h */
#define	SYS_ksem_getvalue	407
#undef SYS_ksem_destroy /* found in: sys/syscall.h */
#define	SYS_ksem_destroy	408
#undef SYS___mac_get_pid /* found in: sys/syscall.h */
#define	SYS___mac_get_pid	409
#undef SYS___mac_get_link /* found in: sys/syscall.h */
#define	SYS___mac_get_link	410
#undef SYS___mac_set_link /* found in: sys/syscall.h */
#define	SYS___mac_set_link	411
#undef SYS_extattr_set_link /* found in: sys/syscall.h */
#define	SYS_extattr_set_link	412
#undef SYS_extattr_get_link /* found in: sys/syscall.h */
#define	SYS_extattr_get_link	413
#undef SYS_extattr_delete_link /* found in: sys/syscall.h */
#define	SYS_extattr_delete_link	414
#undef SYS___mac_execve /* found in: sys/syscall.h */
#define	SYS___mac_execve	415
#undef SYS_sigaction /* found in: sys/syscall.h */
#define	SYS_sigaction	416
#undef SYS_sigreturn /* found in: sys/syscall.h */
#define	SYS_sigreturn	417
#undef SYS_getcontext /* found in: sys/syscall.h */
#define	SYS_getcontext	421
#undef SYS_setcontext /* found in: sys/syscall.h */
#define	SYS_setcontext	422
#undef SYS_swapcontext /* found in: sys/syscall.h */
#define	SYS_swapcontext	423
#undef SYS_freebsd13_swapoff /* found in: sys/syscall.h */
#define	SYS_freebsd13_swapoff	424
#undef SYS___acl_get_link /* found in: sys/syscall.h */
#define	SYS___acl_get_link	425
#undef SYS___acl_set_link /* found in: sys/syscall.h */
#define	SYS___acl_set_link	426
#undef SYS___acl_delete_link /* found in: sys/syscall.h */
#define	SYS___acl_delete_link	427
#undef SYS___acl_aclcheck_link /* found in: sys/syscall.h */
#define	SYS___acl_aclcheck_link	428
#undef SYS_sigwait /* found in: sys/syscall.h */
#define	SYS_sigwait	429
#undef SYS_thr_create /* found in: sys/syscall.h */
#define	SYS_thr_create	430
#undef SYS_thr_exit /* found in: sys/syscall.h */
#define	SYS_thr_exit	431
#undef SYS_thr_self /* found in: sys/syscall.h */
#define	SYS_thr_self	432
#undef SYS_thr_kill /* found in: sys/syscall.h */
#define	SYS_thr_kill	433
#undef SYS_freebsd10__umtx_lock /* found in: sys/syscall.h */
#define	SYS_freebsd10__umtx_lock	434
#undef SYS_freebsd10__umtx_unlock /* found in: sys/syscall.h */
#define	SYS_freebsd10__umtx_unlock	435
#undef SYS_jail_attach /* found in: sys/syscall.h */
#define	SYS_jail_attach	436
#undef SYS_extattr_list_fd /* found in: sys/syscall.h */
#define	SYS_extattr_list_fd	437
#undef SYS_extattr_list_file /* found in: sys/syscall.h */
#define	SYS_extattr_list_file	438
#undef SYS_extattr_list_link /* found in: sys/syscall.h */
#define	SYS_extattr_list_link	439
#undef SYS_ksem_timedwait /* found in: sys/syscall.h */
#define	SYS_ksem_timedwait	441
#undef SYS_thr_suspend /* found in: sys/syscall.h */
#define	SYS_thr_suspend	442
#undef SYS_thr_wake /* found in: sys/syscall.h */
#define	SYS_thr_wake	443
#undef SYS_kldunloadf /* found in: sys/syscall.h */
#define	SYS_kldunloadf	444
#undef SYS_audit /* found in: sys/syscall.h */
#define	SYS_audit	445
#undef SYS_auditon /* found in: sys/syscall.h */
#define	SYS_auditon	446
#undef SYS_getauid /* found in: sys/syscall.h */
#define	SYS_getauid	447
#undef SYS_setauid /* found in: sys/syscall.h */
#define	SYS_setauid	448
#undef SYS_getaudit /* found in: sys/syscall.h */
#define	SYS_getaudit	449
#undef SYS_setaudit /* found in: sys/syscall.h */
#define	SYS_setaudit	450
#undef SYS_getaudit_addr /* found in: sys/syscall.h */
#define	SYS_getaudit_addr	451
#undef SYS_setaudit_addr /* found in: sys/syscall.h */
#define	SYS_setaudit_addr	452
#undef SYS_auditctl /* found in: sys/syscall.h */
#define	SYS_auditctl	453
#undef SYS__umtx_op /* found in: sys/syscall.h */
#define	SYS__umtx_op	454
#undef SYS_thr_new /* found in: sys/syscall.h */
#define	SYS_thr_new	455
#undef SYS_sigqueue /* found in: sys/syscall.h */
#define	SYS_sigqueue	456
#undef SYS_kmq_open /* found in: sys/syscall.h */
#define	SYS_kmq_open	457
#undef SYS_kmq_setattr /* found in: sys/syscall.h */
#define	SYS_kmq_setattr	458
#undef SYS_kmq_timedreceive /* found in: sys/syscall.h */
#define	SYS_kmq_timedreceive	459
#undef SYS_kmq_timedsend /* found in: sys/syscall.h */
#define	SYS_kmq_timedsend	460
#undef SYS_kmq_notify /* found in: sys/syscall.h */
#define	SYS_kmq_notify	461
#undef SYS_kmq_unlink /* found in: sys/syscall.h */
#define	SYS_kmq_unlink	462
#undef SYS_abort2 /* found in: sys/syscall.h */
#define	SYS_abort2	463
#undef SYS_thr_set_name /* found in: sys/syscall.h */
#define	SYS_thr_set_name	464
#undef SYS_aio_fsync /* found in: sys/syscall.h */
#define	SYS_aio_fsync	465
#undef SYS_rtprio_thread /* found in: sys/syscall.h */
#define	SYS_rtprio_thread	466
#undef SYS_sctp_peeloff /* found in: sys/syscall.h */
#define	SYS_sctp_peeloff	471
#undef SYS_sctp_generic_sendmsg /* found in: sys/syscall.h */
#define	SYS_sctp_generic_sendmsg	472
#undef SYS_sctp_generic_sendmsg_iov /* found in: sys/syscall.h */
#define	SYS_sctp_generic_sendmsg_iov	473
#undef SYS_sctp_generic_recvmsg /* found in: sys/syscall.h */
#define	SYS_sctp_generic_recvmsg	474
#undef SYS_pread /* found in: sys/syscall.h */
#define	SYS_pread	475
#undef SYS_pwrite /* found in: sys/syscall.h */
#define	SYS_pwrite	476
#undef SYS_mmap /* found in: sys/syscall.h */
#define	SYS_mmap	477
#undef SYS_lseek /* found in: sys/syscall.h */
#define	SYS_lseek	478
#undef SYS_truncate /* found in: sys/syscall.h */
#define	SYS_truncate	479
#undef SYS_ftruncate /* found in: sys/syscall.h */
#define	SYS_ftruncate	480
#undef SYS_thr_kill2 /* found in: sys/syscall.h */
#define	SYS_thr_kill2	481
#undef SYS_freebsd12_shm_open /* found in: sys/syscall.h */
#define	SYS_freebsd12_shm_open	482
#undef SYS_shm_unlink /* found in: sys/syscall.h */
#define	SYS_shm_unlink	483
#undef SYS_cpuset /* found in: sys/syscall.h */
#define	SYS_cpuset	484
#undef SYS_cpuset_setid /* found in: sys/syscall.h */
#define	SYS_cpuset_setid	485
#undef SYS_cpuset_getid /* found in: sys/syscall.h */
#define	SYS_cpuset_getid	486
#undef SYS_cpuset_getaffinity /* found in: sys/syscall.h */
#define	SYS_cpuset_getaffinity	487
#undef SYS_cpuset_setaffinity /* found in: sys/syscall.h */
#define	SYS_cpuset_setaffinity	488
#undef SYS_faccessat /* found in: sys/syscall.h */
#define	SYS_faccessat	489
#undef SYS_fchmodat /* found in: sys/syscall.h */
#define	SYS_fchmodat	490
#undef SYS_fchownat /* found in: sys/syscall.h */
#define	SYS_fchownat	491
#undef SYS_fexecve /* found in: sys/syscall.h */
#define	SYS_fexecve	492
#undef SYS_freebsd11_fstatat /* found in: sys/syscall.h */
#define	SYS_freebsd11_fstatat	493
#undef SYS_futimesat /* found in: sys/syscall.h */
#define	SYS_futimesat	494
#undef SYS_linkat /* found in: sys/syscall.h */
#define	SYS_linkat	495
#undef SYS_mkdirat /* found in: sys/syscall.h */
#define	SYS_mkdirat	496
#undef SYS_mkfifoat /* found in: sys/syscall.h */
#define	SYS_mkfifoat	497
#undef SYS_freebsd11_mknodat /* found in: sys/syscall.h */
#define	SYS_freebsd11_mknodat	498
#undef SYS_openat /* found in: sys/syscall.h */
#define	SYS_openat	499
#undef SYS_readlinkat /* found in: sys/syscall.h */
#define	SYS_readlinkat	500
#undef SYS_renameat /* found in: sys/syscall.h */
#define	SYS_renameat	501
#undef SYS_symlinkat /* found in: sys/syscall.h */
#define	SYS_symlinkat	502
#undef SYS_unlinkat /* found in: sys/syscall.h */
#define	SYS_unlinkat	503
#undef SYS_posix_openpt /* found in: sys/syscall.h */
#define	SYS_posix_openpt	504
#undef SYS_gssd_syscall /* found in: sys/syscall.h */
#define	SYS_gssd_syscall	505
#undef SYS_jail_get /* found in: sys/syscall.h */
#define	SYS_jail_get	506
#undef SYS_jail_set /* found in: sys/syscall.h */
#define	SYS_jail_set	507
#undef SYS_jail_remove /* found in: sys/syscall.h */
#define	SYS_jail_remove	508
#undef SYS_freebsd12_closefrom /* found in: sys/syscall.h */
#define	SYS_freebsd12_closefrom	509
#undef SYS___semctl /* found in: sys/syscall.h */
#define	SYS___semctl	510
#undef SYS_msgctl /* found in: sys/syscall.h */
#define	SYS_msgctl	511
#undef SYS_shmctl /* found in: sys/syscall.h */
#define	SYS_shmctl	512
#undef SYS_lpathconf /* found in: sys/syscall.h */
#define	SYS_lpathconf	513
#undef SYS___cap_rights_get /* found in: sys/syscall.h */
#define	SYS___cap_rights_get	515
#undef SYS_cap_enter /* found in: sys/syscall.h */
#define	SYS_cap_enter	516
#undef SYS_cap_getmode /* found in: sys/syscall.h */
#define	SYS_cap_getmode	517
#undef SYS_pdfork /* found in: sys/syscall.h */
#define	SYS_pdfork	518
#undef SYS_pdkill /* found in: sys/syscall.h */
#define	SYS_pdkill	519
#undef SYS_pdgetpid /* found in: sys/syscall.h */
#define	SYS_pdgetpid	520
#undef SYS_pselect /* found in: sys/syscall.h */
#define	SYS_pselect	522
#undef SYS_getloginclass /* found in: sys/syscall.h */
#define	SYS_getloginclass	523
#undef SYS_setloginclass /* found in: sys/syscall.h */
#define	SYS_setloginclass	524
#undef SYS_rctl_get_racct /* found in: sys/syscall.h */
#define	SYS_rctl_get_racct	525
#undef SYS_rctl_get_rules /* found in: sys/syscall.h */
#define	SYS_rctl_get_rules	526
#undef SYS_rctl_get_limits /* found in: sys/syscall.h */
#define	SYS_rctl_get_limits	527
#undef SYS_rctl_add_rule /* found in: sys/syscall.h */
#define	SYS_rctl_add_rule	528
#undef SYS_rctl_remove_rule /* found in: sys/syscall.h */
#define	SYS_rctl_remove_rule	529
#undef SYS_posix_fallocate /* found in: sys/syscall.h */
#define	SYS_posix_fallocate	530
#undef SYS_posix_fadvise /* found in: sys/syscall.h */
#define	SYS_posix_fadvise	531
#undef SYS_wait6 /* found in: sys/syscall.h */
#define	SYS_wait6	532
#undef SYS_cap_rights_limit /* found in: sys/syscall.h */
#define	SYS_cap_rights_limit	533
#undef SYS_cap_ioctls_limit /* found in: sys/syscall.h */
#define	SYS_cap_ioctls_limit	534
#undef SYS_cap_ioctls_get /* found in: sys/syscall.h */
#define	SYS_cap_ioctls_get	535
#undef SYS_cap_fcntls_limit /* found in: sys/syscall.h */
#define	SYS_cap_fcntls_limit	536
#undef SYS_cap_fcntls_get /* found in: sys/syscall.h */
#define	SYS_cap_fcntls_get	537
#undef SYS_bindat /* found in: sys/syscall.h */
#define	SYS_bindat	538
#undef SYS_connectat /* found in: sys/syscall.h */
#define	SYS_connectat	539
#undef SYS_chflagsat /* found in: sys/syscall.h */
#define	SYS_chflagsat	540
#undef SYS_accept4 /* found in: sys/syscall.h */
#define	SYS_accept4	541
#undef SYS_pipe2 /* found in: sys/syscall.h */
#define	SYS_pipe2	542
#undef SYS_aio_mlock /* found in: sys/syscall.h */
#define	SYS_aio_mlock	543
#undef SYS_procctl /* found in: sys/syscall.h */
#define	SYS_procctl	544
#undef SYS_ppoll /* found in: sys/syscall.h */
#define	SYS_ppoll	545
#undef SYS_futimens /* found in: sys/syscall.h */
#define	SYS_futimens	546
#undef SYS_utimensat /* found in: sys/syscall.h */
#define	SYS_utimensat	547
#undef SYS_fdatasync /* found in: sys/syscall.h */
#define	SYS_fdatasync	550
#undef SYS_fstat /* found in: sys/syscall.h */
#define	SYS_fstat	551
#undef SYS_fstatat /* found in: sys/syscall.h */
#define	SYS_fstatat	552
#undef SYS_fhstat /* found in: sys/syscall.h */
#define	SYS_fhstat	553
#undef SYS_getdirentries /* found in: sys/syscall.h */
#define	SYS_getdirentries	554
#undef SYS_statfs /* found in: sys/syscall.h */
#define	SYS_statfs	555
#undef SYS_fstatfs /* found in: sys/syscall.h */
#define	SYS_fstatfs	556
#undef SYS_getfsstat /* found in: sys/syscall.h */
#define	SYS_getfsstat	557
#undef SYS_fhstatfs /* found in: sys/syscall.h */
#define	SYS_fhstatfs	558
#undef SYS_mknodat /* found in: sys/syscall.h */
#define	SYS_mknodat	559
#undef SYS_kevent /* found in: sys/syscall.h */
#define	SYS_kevent	560
#undef SYS_cpuset_getdomain /* found in: sys/syscall.h */
#define	SYS_cpuset_getdomain	561
#undef SYS_cpuset_setdomain /* found in: sys/syscall.h */
#define	SYS_cpuset_setdomain	562
#undef SYS_getrandom /* found in: sys/syscall.h */
#define	SYS_getrandom	563
#undef SYS_getfhat /* found in: sys/syscall.h */
#define	SYS_getfhat	564
#undef SYS_fhlink /* found in: sys/syscall.h */
#define	SYS_fhlink	565
#undef SYS_fhlinkat /* found in: sys/syscall.h */
#define	SYS_fhlinkat	566
#undef SYS_fhreadlink /* found in: sys/syscall.h */
#define	SYS_fhreadlink	567
#undef SYS_funlinkat /* found in: sys/syscall.h */
#define	SYS_funlinkat	568
#undef SYS_copy_file_range /* found in: sys/syscall.h */
#define	SYS_copy_file_range	569
#undef SYS___sysctlbyname /* found in: sys/syscall.h */
#define	SYS___sysctlbyname	570
#undef SYS_shm_open2 /* found in: sys/syscall.h */
#define	SYS_shm_open2	571
#undef SYS_shm_rename /* found in: sys/syscall.h */
#define	SYS_shm_rename	572
#undef SYS_sigfastblock /* found in: sys/syscall.h */
#define	SYS_sigfastblock	573
#undef SYS___realpathat /* found in: sys/syscall.h */
#define	SYS___realpathat	574
#undef SYS_close_range /* found in: sys/syscall.h */
#define	SYS_close_range	575
#undef SYS_rpctls_syscall /* found in: sys/syscall.h */
#define	SYS_rpctls_syscall	576
#undef SYS___specialfd /* found in: sys/syscall.h */
#define	SYS___specialfd	577
#undef SYS_aio_writev /* found in: sys/syscall.h */
#define	SYS_aio_writev	578
#undef SYS_aio_readv /* found in: sys/syscall.h */
#define	SYS_aio_readv	579
#undef SYS_fspacectl /* found in: sys/syscall.h */
#define	SYS_fspacectl	580
#undef SYS_sched_getcpu /* found in: sys/syscall.h */
#define	SYS_sched_getcpu	581
#undef SYS_swapoff /* found in: sys/syscall.h */
#define	SYS_swapoff	582
#undef CTL_MAXNAME /* found in: sys/sysctl.h */
#define	CTL_MAXNAME	24	/* largest number of components supported */
#undef CTL_KERN /* found in: sys/sysctl.h */
#define	CTL_KERN	1		/* "high kernel": proc, limits */
#undef CTL_NET /* found in: sys/sysctl.h */
#define	CTL_NET		4		/* network, see socket.h */
#undef CTL_HW /* found in: sys/sysctl.h */
#define	CTL_HW		6		/* generic cpu/io */
#undef CTL_VFS /* found in: sys/sysctl.h */
#define	CTL_VFS		3		/* filesystem, mount type is next */
#undef HW_NCPU /* found in: sys/sysctl.h */
#define	HW_NCPU		 3		/* int: number of cpus */
#undef HW_MACHINE /* found in: sys/sysctl.h */
#define	HW_MACHINE	 1		/* string: machine class */
#undef HW_MACHINE_ARCH /* found in: sys/sysctl.h */
#define	HW_MACHINE_ARCH	11		/* string: machine architecture */
#undef KERN_PROC /* found in: sys/sysctl.h */
#define	KERN_PROC		14	/* struct: process entries */
#undef KERN_PROC_ALL /* found in: sys/sysctl.h */
#define	KERN_PROC_ALL		0	/* everything */
#undef KERN_PROC_PROC /* found in: sys/sysctl.h */
#define	KERN_PROC_PROC		8	/* only return procs */
#undef KERN_PROC_PID /* found in: sys/sysctl.h */
#define	KERN_PROC_PID		1	/* by process id */
#undef KERN_PROC_PGRP /* found in: sys/sysctl.h */
#define	KERN_PROC_PGRP		2	/* by process group id */
#undef KERN_PROC_INC_THREAD /* found in: sys/sysctl.h */
#define	KERN_PROC_INC_THREAD	0x10	/* */
#undef KERN_PROC_PATHNAME /* found in: sys/sysctl.h */
#define	KERN_PROC_PATHNAME	12	/* path to executable */
#undef KERN_PROC_ARGS /* found in: sys/sysctl.h */
#define	KERN_PROC_ARGS		7	/* get/set arguments/proctitle */
#undef KERN_PROC_SESSION /* found in: sys/sysctl.h */
#define	KERN_PROC_SESSION	3	/* by session of pid */
#undef KERN_PROC_TTY /* found in: sys/sysctl.h */
#define	KERN_PROC_TTY		4	/* by controlling tty */
#undef KERN_PROC_RUID /* found in: sys/sysctl.h */
#define	KERN_PROC_RUID		6	/* by real uid */
#undef KERN_PROC_FILEDESC /* found in: sys/sysctl.h */
#define	KERN_PROC_FILEDESC	33	/* File descriptors for process */
#undef KERN_PROC_UID /* found in: sys/sysctl.h */
#define	KERN_PROC_UID		5	/* by effective uid */
#undef KERN_PROC_VMMAP /* found in: sys/sysctl.h */
#define	KERN_PROC_VMMAP		32	/* VM map entries for process */
#undef KERN_USRSTACK /* found in: sys/sysctl.h */
#define	KERN_USRSTACK		33	/* int: address of USRSTACK */
#undef KERN_PS_STRINGS /* found in: sys/sysctl.h */
#define	KERN_PS_STRINGS		32	/* int: address of PS_STRINGS */
#undef CTL_SYSCTL /* found in: sys/sysctl.h */
#define	CTL_SYSCTL	0		/* "magic" numbers */
#undef CTL_SYSCTL_NEXT /* found in: sys/sysctl.h */
#define	CTL_SYSCTL_NEXT		2	/* next OID, honoring CTLFLAG_SKIP */
#undef CTL_SYSCTL_NAME2OID /* found in: sys/sysctl.h */
#define	CTL_SYSCTL_NAME2OID	3	/* int array of name */
#undef CTL_SYSCTL_OIDFMT /* found in: sys/sysctl.h */
#define	CTL_SYSCTL_OIDFMT	4	/* OID's kind and format */
#undef CTL_SYSCTL_OIDDESCR /* found in: sys/sysctl.h */
#define	CTL_SYSCTL_OIDDESCR	5	/* OID's description */
#undef CTL_SYSCTL_OIDLABEL /* found in: sys/sysctl.h */
#define	CTL_SYSCTL_OIDLABEL	6	/* aggregation label */
#undef CTL_SYSCTL_NEXTNOSKIP /* found in: sys/sysctl.h */
#define	CTL_SYSCTL_NEXTNOSKIP	7	/* next OID, ignoring CTLFLAG_SKIP */
#undef CTLTYPE /* found in: sys/sysctl.h */
#define	CTLTYPE		0xf	/* mask for the type */
#undef CTLTYPE_INT /* found in: sys/sysctl.h */
#define	CTLTYPE_INT	2	/* name describes an integer */
#undef CTLTYPE_UINT /* found in: sys/sysctl.h */
#define	CTLTYPE_UINT	6	/* name describes an unsigned integer */
#undef CTLTYPE_LONG /* found in: sys/sysctl.h */
#define	CTLTYPE_LONG	7	/* name describes a long */
#undef CTLTYPE_ULONG /* found in: sys/sysctl.h */
#define	CTLTYPE_ULONG	8	/* name describes an unsigned long */
#undef CTLTYPE_S8 /* found in: sys/sysctl.h */
#define	CTLTYPE_S8	0xc	/* name describes a signed 8-bit number */
#undef CTLTYPE_S16 /* found in: sys/sysctl.h */
#define	CTLTYPE_S16	0xd	/* name describes a signed 16-bit number */
#undef CTLTYPE_S32 /* found in: sys/sysctl.h */
#define	CTLTYPE_S32	0xe	/* name describes a signed 32-bit number */
#undef CTLTYPE_S64 /* found in: sys/sysctl.h */
#define	CTLTYPE_S64	4	/* name describes a signed 64-bit number */
#undef CTLTYPE_U8 /* found in: sys/sysctl.h */
#define	CTLTYPE_U8	0xa	/* name describes an unsigned 8-bit number */
#undef CTLTYPE_U16 /* found in: sys/sysctl.h */
#define	CTLTYPE_U16	0xb	/* name describes an unsigned 16-bit number */
#undef CTLTYPE_U32 /* found in: sys/sysctl.h */
#define	CTLTYPE_U32	0xf	/* name describes an unsigned 32-bit number */
#undef CTLTYPE_U64 /* found in: sys/sysctl.h */
#define	CTLTYPE_U64	9	/* name describes an unsigned 64-bit number */
#undef UMTX_OP_SHM /* found in: sys/umtx.h */
#define	UMTX_OP_SHM		25
#undef UMTX_OP_WAIT_UINT /* found in: sys/umtx.h */
#define	UMTX_OP_WAIT_UINT	11
#undef UMTX_OP_WAIT_UINT_PRIVATE /* found in: sys/umtx.h */
#define	UMTX_OP_WAIT_UINT_PRIVATE	15
#undef UMTX_OP_WAIT /* found in: sys/umtx.h */
#define	UMTX_OP_WAIT		2
#undef UMTX_OP_WAKE /* found in: sys/umtx.h */
#define	UMTX_OP_WAKE		3
#undef UMTX_OP_MUTEX_TRYLOCK /* found in: sys/umtx.h */
#define	UMTX_OP_MUTEX_TRYLOCK	4
#undef UMTX_OP_MUTEX_LOCK /* found in: sys/umtx.h */
#define	UMTX_OP_MUTEX_LOCK	5
#undef UMTX_OP_MUTEX_UNLOCK /* found in: sys/umtx.h */
#define	UMTX_OP_MUTEX_UNLOCK	6
#undef UMTX_OP_CV_WAIT /* found in: sys/umtx.h */
#define	UMTX_OP_CV_WAIT		8
#undef UMTX_OP_CV_SIGNAL /* found in: sys/umtx.h */
#define	UMTX_OP_CV_SIGNAL	9
#undef UMTX_OP_CV_BROADCAST /* found in: sys/umtx.h */
#define	UMTX_OP_CV_BROADCAST	10
#undef UMTX_OP_RW_RDLOCK /* found in: sys/umtx.h */
#define	UMTX_OP_RW_RDLOCK	12
#undef UMTX_OP_RW_WRLOCK /* found in: sys/umtx.h */
#define	UMTX_OP_RW_WRLOCK	13
#undef UMTX_OP_RW_UNLOCK /* found in: sys/umtx.h */
#define	UMTX_OP_RW_UNLOCK	14
#undef UMTX_OP_WAKE_PRIVATE /* found in: sys/umtx.h */
#define	UMTX_OP_WAKE_PRIVATE	16
#undef UMTX_OP_SEM2_WAIT /* found in: sys/umtx.h */
#define	UMTX_OP_SEM2_WAIT	23
#undef UMTX_OP_SEM2_WAKE /* found in: sys/umtx.h */
#define	UMTX_OP_SEM2_WAKE	24
#undef UMTX_OP_ROBUST_LISTS /* found in: sys/umtx.h */
#define	UMTX_OP_ROBUST_LISTS	26
#undef UMTX_OP_MUTEX_WAIT /* found in: sys/umtx.h */
#define	UMTX_OP_MUTEX_WAIT	17
#undef UMTX_OP_MUTEX_WAKE /* found in: sys/umtx.h */
#define	UMTX_OP_MUTEX_WAKE	18	/* deprecated */
#undef UMTX_OP_SEM_WAIT /* found in: sys/umtx.h */
#define	UMTX_OP_SEM_WAIT	19	/* deprecated */
#undef UMTX_OP_SEM_WAKE /* found in: sys/umtx.h */
#define	UMTX_OP_SEM_WAKE	20	/* deprecated */
/* Auto generated by: sym_extract.py /home/sobomax/projects/freebsd13/sys/netinet syms_netinet.econf */
/* From Git revision: 74b6c983723cf3d3e277f10780ad081e32c80e80 branch: releng/14.1 */

/* Defines: */
#undef IP_RECVOPTS /* found in: netinet/in.h */
#define	IP_RECVOPTS		5    /* bool; receive all IP opts w/dgram */
#undef IP_RECVDSTADDR /* found in: netinet/in.h */
#define	IP_RECVDSTADDR		7    /* bool; receive IP dst addr w/dgram */
#undef IP_RECVRETOPTS /* found in: netinet/in.h */
#define	IP_RECVRETOPTS		6    /* bool; receive IP opts for response */
#undef IP_PORTRANGE /* found in: netinet/in.h */
#define	IP_PORTRANGE		19   /* int; range to choose for unspec port */
#undef IP_RECVIF /* found in: netinet/in.h */
#define	IP_RECVIF		20   /* bool; receive reception if w/dgram */
#undef IP_RETOPTS /* found in: netinet/in.h */
#define	IP_RETOPTS		8    /* ip_opts; set/get IP options */
#undef IP_BINDANY /* found in: netinet/in.h */
#define	IP_BINDANY		24   /* bool: allow bind to any address */
#undef IP_ONESBCAST /* found in: netinet/in.h */
#define	IP_ONESBCAST		23   /* bool: send all-ones broadcast */
/* Auto generated by: sym_extract.py /home/sobomax/projects/freebsd13/sys/netinet6 syms_netinet6.econf */
/* From Git revision: 74b6c983723cf3d3e277f10780ad081e32c80e80 branch: releng/14.1 */

/* Defines: */
#undef IPV6_MULTICAST_HOPS /* found in: netinet6/in6.h */
#define IPV6_MULTICAST_HOPS	10 /* int; set/get IP6 multicast hops */
#undef IPV6_IPSEC_POLICY /* found in: netinet6/in6.h */
#define IPV6_IPSEC_POLICY	28 /* struct; get/set security policy */
#undef IPV6_PORTRANGE /* found in: netinet6/in6.h */
#define IPV6_PORTRANGE		14 /* int; range to choose for unspec port */
#undef IPV6_USE_MIN_MTU /* found in: netinet6/in6.h */
#define IPV6_USE_MIN_MTU	42 /* bool; send packets at the minimum MTU */
#undef IPV6_PREFER_TEMPADDR /* found in: netinet6/in6.h */
#define IPV6_PREFER_TEMPADDR	63 /* int; prefer temporary addresses as */
#undef IPV6_BINDANY /* found in: netinet6/in6.h */
#define	IPV6_BINDANY		64 /* bool: allow bind to any address */
#undef ICMP6_FILTER /* found in: netinet6/in6.h */
#define ICMP6_FILTER		18 /* icmp6_filter; icmp6 filter */
#undef IPV6_FW_ADD /* found in: netinet6/in6.h */
#define IPV6_FW_ADD		30 /* add a firewall rule to chain */
#undef IPV6_FW_DEL /* found in: netinet6/in6.h */
#define IPV6_FW_DEL		31 /* delete a firewall rule from chain */
#undef IPV6_FW_FLUSH /* found in: netinet6/in6.h */
#define IPV6_FW_FLUSH		32 /* flush firewall rule chain */
#undef IPV6_FW_ZERO /* found in: netinet6/in6.h */
#define IPV6_FW_ZERO		33 /* clear single/all firewall counter(s) */
#undef IPV6_FW_GET /* found in: netinet6/in6.h */
#define IPV6_FW_GET		34 /* get entire firewall rule chain */
#undef IPV6_MSFILTER /* found in: netinet6/in6.h */
#define	IPV6_MSFILTER		74 /* struct __msfilterreq; */
